// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef COUNTFILESPARAMS_H
#define COUNTFILESPARAMS_H
#include "regexppath.h"
#include <QMetaType>
#include <QString>

class CountFilesParams {

public:
    CountFilesParams();
    CountFilesParams(const QString& path, const RegExpPath& filter, bool notBinary);
    CountFilesParams(const QString& path, const RegExpPath& filter, bool cacheFileList, int total,
                     int filtered, bool notBinary);
    QString path() const;
    void setPath(const QString& value);
    RegExpPath filter() const;
    void setFilter(const RegExpPath& value);
    bool cacheFileList() const;
    void setCacheFileList(bool value);
    int total() const;
    void setTotal(int value);
    int filtered() const;
    void setFiltered(int value);
    bool notBinary() const;
    void setNotBinary(bool value);

protected:
    QString mPath;
    RegExpPath mFilter;
    bool mCacheFileList;
    int mTotal;
    int mFiltered;
    bool mNotBinary;
};

Q_DECLARE_METATYPE(CountFilesParams)

#endif // COUNTFILESPARAMS_H
