// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef COUNTFILESPARAMS_H
#define COUNTFILESPARAMS_H
#include "regexppath.h"
#include <QMetaType>
#include <QString>

class CountFilesParams {

public:
    CountFilesParams();
    CountFilesParams(const QString& path, const RegExpPath& filter, int total, int filtered);
    QString path() const;
    void setPath(const QString& value);
    RegExpPath filter() const;
    void setFilter(const RegExpPath& value);
    int total() const;
    void setTotal(int value);
    int filtered() const;
    void setFiltered(int value);

protected:
    QString mPath;
    RegExpPath mFilter;
    int mTotal;
    int mFiltered;
};

Q_DECLARE_METATYPE(CountFilesParams)

#endif // COUNTFILESPARAMS_H
