// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "countfilesparams.h"

CountFilesParams::CountFilesParams() : mTotal(-1), mFiltered(-1) {
}
CountFilesParams::CountFilesParams(const QString& path, const RegExpPath& filter, int total,
                                   int filtered)
    : mPath(path), mFilter(filter), mTotal(total), mFiltered(filtered) {
}
QString CountFilesParams::path() const {
    return mPath;
}
void CountFilesParams::setPath(const QString& value) {
    mPath = value;
}
RegExpPath CountFilesParams::filter() const {
    return mFilter;
}
void CountFilesParams::setFilter(const RegExpPath& value) {
    mFilter = value;
}
int CountFilesParams::total() const {
    return mTotal;
}
void CountFilesParams::setTotal(int value) {
    mTotal = value;
}
int CountFilesParams::filtered() const {
    return mFiltered;
}
void CountFilesParams::setFiltered(int value) {
    mFiltered = value;
}
