// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "displayoptions.h"

DisplayOptions::DisplayOptions() : mLinesBefore(0), mLinesAfter(0) {
}
DisplayOptions::DisplayOptions(int linesBefore, int linesAfter)
    : mLinesBefore(linesBefore), mLinesAfter(linesAfter) {
}
int DisplayOptions::linesBefore() const {
    return mLinesBefore;
}
void DisplayOptions::setLinesBefore(int value) {
    mLinesBefore = value;
}
int DisplayOptions::linesAfter() const {
    return mLinesAfter;
}
void DisplayOptions::setLinesAfter(int value) {
    mLinesAfter = value;
}
