// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef DISPLAYOPTIONS_H
#define DISPLAYOPTIONS_H

class DisplayOptions {

public:
    DisplayOptions();
    DisplayOptions(int linesBefore, int linesAfter);
    int linesBefore() const;
    void setLinesBefore(int value);
    int linesAfter() const;
    void setLinesAfter(int value);

protected:
    int mLinesBefore;
    int mLinesAfter;
};

#endif // DISPLAYOPTIONS_H
