// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef EDITOR_H
#define EDITOR_H
#include <QJsonObject>
#include <QRegularExpression>
#include <QString>

class Editor {

public:
    enum class Type { NotSpecified, VsCode, QtCreator, Geany };

    Editor();
    Editor(const QString& exts, const QString& app, Editor::Type type = Type::NotSpecified);
    QString name() const;
    void setExts(const QString& value);
    bool isNull() const;
    bool matches(const QString& ext) const;
    static Editor fromJson(const QJsonObject& json);
    QJsonObject toJson() const;
    QString exts() const;
    QString app() const;
    void setApp(const QString& value);
    Type type() const;
    void setType(Editor::Type value);
    QRegularExpression exp() const;
    void setExp(const QRegularExpression& value);

protected:
    QString mExts;
    QString mApp;
    Type mType;
    QRegularExpression mExp;
};

#endif // EDITOR_H
