// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef GETLISTINGPARAMS_H
#define GETLISTINGPARAMS_H
#include <QMetaType>
#include <QString>

class GetListingParams {

public:
    GetListingParams();
    GetListingParams(const QString& path, bool cacheFileList);
    QString path() const;
    void setPath(const QString& value);
    bool cacheFileList() const;
    void setCacheFileList(bool value);

protected:
    QString mPath;
    bool mCacheFileList;
};

Q_DECLARE_METATYPE(GetListingParams)

#endif // GETLISTINGPARAMS_H
