// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "getlistingparams.h"

GetListingParams::GetListingParams() : mCacheFileList(false) {
}
GetListingParams::GetListingParams(const QString& path, bool cacheFileList)
    : mPath(path), mCacheFileList(cacheFileList) {
}
QString GetListingParams::path() const {
    return mPath;
}
void GetListingParams::setPath(const QString& value) {
    mPath = value;
}
bool GetListingParams::cacheFileList() const {
    return mCacheFileList;
}
void GetListingParams::setCacheFileList(bool value) {
    mCacheFileList = value;
}
