// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "regexpreplacement.h"

RegExpReplacement::RegExpReplacement() : mPreserveCase(false), mRenameFiles(true) {
}
RegExpReplacement::RegExpReplacement(const QString& pattern, bool preserveCase, bool renameFiles)
    : mPattern(pattern), mPreserveCase(preserveCase), mRenameFiles(renameFiles) {
}
QString RegExpReplacement::pattern() const {
    return mPattern;
}
void RegExpReplacement::setPattern(const QString& value) {
    mPattern = value;
}
bool RegExpReplacement::preserveCase() const {
    return mPreserveCase;
}
void RegExpReplacement::setPreserveCase(bool value) {
    mPreserveCase = value;
}
bool RegExpReplacement::renameFiles() const {
    return mRenameFiles;
}
void RegExpReplacement::setRenameFiles(bool value) {
    mRenameFiles = value;
}
