// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "regexpreplacement.h"

RegExpReplacement::RegExpReplacement() : mPreserveCase(false) {
}
RegExpReplacement::RegExpReplacement(const QString& pattern, bool preserveCase)
    : mPattern(pattern), mPreserveCase(preserveCase) {
}
QString RegExpReplacement::pattern() const {
    return mPattern;
}
void RegExpReplacement::setPattern(const QString& value) {
    mPattern = value;
}
bool RegExpReplacement::preserveCase() const {
    return mPreserveCase;
}
void RegExpReplacement::setPreserveCase(bool value) {
    mPreserveCase = value;
}
