// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef REGEXPREPLACEMENT_H
#define REGEXPREPLACEMENT_H
#include <QMetaType>
#include <QString>

class RegExpReplacement {

public:
    RegExpReplacement();
    RegExpReplacement(const QString& pattern, bool preserveCase);
    QString pattern() const;
    void setPattern(const QString& value);
    bool preserveCase() const;
    void setPreserveCase(bool value);

protected:
    QString mPattern;
    bool mPreserveCase;
};

Q_DECLARE_METATYPE(RegExpReplacement)

#endif // REGEXPREPLACEMENT_H
