// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef RENAMEPARAMS_H
#define RENAMEPARAMS_H
#include <QList>
#include <QMetaType>
#include <QPair>
#include <QString>

class RenameParams {

public:
    RenameParams();
    RenameParams(const QList<QPair<QString, QString>>& renames);
    QList<QPair<QString, QString>> renames() const;
    void setRenames(const QList<QPair<QString, QString>>& value);

protected:
    QList<QPair<QString, QString>> mRenames;
};

Q_DECLARE_METATYPE(RenameParams)

#endif // RENAMEPARAMS_H
