// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "renameparams.h"

RenameParams::RenameParams() {
}
RenameParams::RenameParams(const QList<QPair<QString, QString>>& renames) : mRenames(renames) {
}
QList<QPair<QString, QString>> RenameParams::renames() const {
    return mRenames;
}
void RenameParams::setRenames(const QList<QPair<QString, QString>>& value) {
    mRenames = value;
}
