// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "replaceparams.h"

ReplaceParams::ReplaceParams() {
}
ReplaceParams::ReplaceParams(const QString& path, const QList<ReplaceItem>& items)
    : mPath(path), mItems(items) {
}
QString ReplaceParams::path() const {
    return mPath;
}
void ReplaceParams::setPath(const QString& value) {
    mPath = value;
}
QList<ReplaceItem> ReplaceParams::items() const {
    return mItems;
}
void ReplaceParams::setItems(const QList<ReplaceItem>& value) {
    mItems = value;
}
