// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "replaceparams.h"

ReplaceParams::ReplaceParams() {
}
ReplaceParams::ReplaceParams(const QList<ReplaceFile>& files) : mFiles(files) {
}
QList<ReplaceFile> ReplaceParams::files() const {
    return mFiles;
}
void ReplaceParams::setFiles(const QList<ReplaceFile>& value) {
    mFiles = value;
}
void ReplaceParams::append(const ReplaceFile& file) {
    mFiles.append(file);
}
int ReplaceParams::size() const {
    return mFiles.size();
}
