// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef REPLACEDPARAMS_H
#define REPLACEDPARAMS_H
#include <QList>
#include <QMetaType>
#include <QPair>
#include <QString>

class ReplacedParams {

public:
    ReplacedParams();
    ReplacedParams(int countFiles, int countLines, const QList<QPair<QString, QString>>& renames);
    int countFiles() const;
    void setCountFiles(int value);
    int countLines() const;
    void setCountLines(int value);
    QList<QPair<QString, QString>> renames() const;
    void setRenames(const QList<QPair<QString, QString>>& value);

protected:
    int mCountFiles;
    int mCountLines;
    QList<QPair<QString, QString>> mRenames;
};

Q_DECLARE_METATYPE(ReplacedParams)

#endif // REPLACEDPARAMS_H
