// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef REPLACEPARAMS_H
#define REPLACEPARAMS_H
#include <QList>
#include <QMetaType>
#include <QString>

class ReplaceParams {

public:
    ReplaceParams();
    ReplaceParams(const QString& path, const QList<ReplaceItem>& items);
    QString path() const;
    void setPath(const QString& value);
    QList<ReplaceItem> items() const;
    void setItems(const QList<ReplaceItem>& value);

protected:
    QString mPath;
    QList<ReplaceItem> mItems;
};

Q_DECLARE_METATYPE(ReplaceParams)

#endif // REPLACEPARAMS_H
