// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "replacefile.h"

ReplaceFile::ReplaceFile() {
}
ReplaceFile::ReplaceFile(const QString& path) : mPath(path) {
}
QString ReplaceFile::path() const {
    return mPath;
}
void ReplaceFile::setPath(const QString& value) {
    mPath = value;
}
QList<ReplaceItem> ReplaceFile::items() const {
    return mItems;
}
void ReplaceFile::setItems(const QList<ReplaceItem>& value) {
    mItems = value;
}
void ReplaceFile::append(const ReplaceItem& item) {
    mItems.append(item);
}
int ReplaceFile::size() const {
    return mItems.size();
}
