// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef REPLACEPARAMS_H
#define REPLACEPARAMS_H
#include "replacefile.h"
#include <QList>
#include <QMetaType>

class ReplaceParams {

public:
    ReplaceParams();
    ReplaceParams(const QList<ReplaceFile>& files);
    void append(const ReplaceFile& file);
    int size() const;
    QList<ReplaceFile> files() const;
    void setFiles(const QList<ReplaceFile>& value);

protected:
    QList<ReplaceFile> mFiles;
};

Q_DECLARE_METATYPE(ReplaceParams)

#endif // REPLACEPARAMS_H
