// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef REPLACEFILE_H
#define REPLACEFILE_H
#include "replaceitem.h"
#include <QList>
#include <QMetaType>
#include <QString>

class ReplaceFile {

public:
    ReplaceFile();
    ReplaceFile(const QString& path);
    void append(const ReplaceItem& item);
    int size() const;
    QString path() const;
    void setPath(const QString& value);
    QList<ReplaceItem> items() const;
    void setItems(const QList<ReplaceItem>& value);

protected:
    QString mPath;
    QList<ReplaceItem> mItems;
};

Q_DECLARE_METATYPE(ReplaceFile)

#endif // REPLACEFILE_H
