// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "replacedparams.h"

ReplacedParams::ReplacedParams() {
}
ReplacedParams::ReplacedParams(int countFiles, int countLines,
                               const QList<QPair<QString, QString>>& renames)
    : mCountFiles(countFiles), mCountLines(countLines), mRenames(renames) {
}
int ReplacedParams::countFiles() const {
    return mCountFiles;
}
void ReplacedParams::setCountFiles(int value) {
    mCountFiles = value;
}
int ReplacedParams::countLines() const {
    return mCountLines;
}
void ReplacedParams::setCountLines(int value) {
    mCountLines = value;
}
QList<QPair<QString, QString>> ReplacedParams::renames() const {
    return mRenames;
}
void ReplacedParams::setRenames(const QList<QPair<QString, QString>>& value) {
    mRenames = value;
}
