// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHNAMEHITS_H
#define SEARCHNAMEHITS_H
class QString;
#include "regexppair.h"
#include <QMetaType>
#include <QStringList>

class SearchNameHits {

public:
    SearchNameHits();
    SearchNameHits(const RegExpPair& pattern);
    void append(const SearchNameHits& hits);
    void append(const QString& path);
    void clear();
    RegExpPair pattern() const;
    void setPattern(const RegExpPair& value);
    QStringList hits() const;
    void setHits(const QStringList& value);

protected:
    RegExpPair mPattern;
    QStringList mHits;
};

Q_DECLARE_METATYPE(SearchNameHits)

#endif // SEARCHNAMEHITS_H
