// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHHIT_H
#define SEARCHHIT_H
#include <QList>
#include <QMap>
#include <QMetaType>
#include <QSet>
#include <QString>

class SearchHit {

public:
    SearchHit();
    SearchHit(const QString& path, const QString& relativePath, const QList<int>& hits,
              const QMap<int, QString>& cache = QMap<int, QString>());
    QSet<int> siblings(int before, int after) const;
    void read(int before, int after);
    QString path() const;
    void setPath(const QString& value);
    QString relativePath() const;
    void setRelativePath(const QString& value);
    QList<int> hits() const;
    void setHits(const QList<int>& value);
    QMap<int, QString> cache() const;
    void setCache(const QMap<int, QString>& value);

protected:
    QString mPath;
    QString mRelativePath;
    QList<int> mHits;
    QMap<int, QString> mCache;
};

Q_DECLARE_METATYPE(SearchHit)

#endif // SEARCHHIT_H
