// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "searchparams.h"

SearchParams::SearchParams() : mId(-1) {
}
int SearchParams::id() const {
    return mId;
}
void SearchParams::setId(int value) {
    mId = value;
}
int SearchParams::mode() const {
    return mMode;
}
void SearchParams::setMode(int value) {
    mMode = value;
}
QString SearchParams::path() const {
    return mPath;
}
void SearchParams::setPath(const QString& value) {
    mPath = value;
}
RegExp SearchParams::pattern() const {
    return mPattern;
}
void SearchParams::setPattern(const RegExp& value) {
    mPattern = value;
}
RegExpPath SearchParams::filter() const {
    return mFilter;
}
void SearchParams::setFilter(const RegExpPath& value) {
    mFilter = value;
}
RegExpReplacement SearchParams::replacement() const {
    return mReplacement;
}
void SearchParams::setReplacement(const RegExpReplacement& value) {
    mReplacement = value;
}
bool SearchParams::cacheFileList() const {
    return mCacheFileList;
}
void SearchParams::setCacheFileList(bool value) {
    mCacheFileList = value;
}
bool SearchParams::skipBinary() const {
    return mSkipBinary;
}
void SearchParams::setSkipBinary(bool value) {
    mSkipBinary = value;
}
