// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "searchnamehits.h"
#include <QString>

SearchNameHits::SearchNameHits() {
}
SearchNameHits::SearchNameHits(const RegExp& pattern) : mPattern(pattern) {
}
RegExp SearchNameHits::pattern() const {
    return mPattern;
}
void SearchNameHits::setPattern(const RegExp& value) {
    mPattern = value;
}
QStringList SearchNameHits::hits() const {
    return mHits;
}
void SearchNameHits::setHits(const QStringList& value) {
    mHits = value;
}
void SearchNameHits::append(const SearchNameHits& hits) {
    mPattern = hits.pattern();
    mHits.append(hits.hits());
}
void SearchNameHits::append(const QString& path) {
    mHits.append(path);
}
void SearchNameHits::clear() {
    mHits.clear();
}
