// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHDATA_H
#define SEARCHDATA_H
#include <QString>
#include <QStringList>

class SearchData {

public:
    SearchData();
    SearchData(const QStringList& files, int filesFiltered, int dirsFiltered);
    QString file(int i) const;
    int filesSize() const;
    QStringList files() const;
    void setFiles(const QStringList& value);
    int filesFiltered() const;
    void setFilesFiltered(int value);
    int dirsFiltered() const;
    void setDirsFiltered(int value);
    int filesComplete() const;
    void setFilesComplete(int value);

protected:
    QStringList mFiles;
    int mFilesFiltered;
    int mDirsFiltered;
    int mFilesComplete;
};

#endif // SEARCHDATA_H
