// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHTAB_H
#define SEARCHTAB_H
#include <QWidget>
class QTextBrowser;
#include "coloredline.h"
#include "displayoptionswidget.h"
#include "html.h"
#include "searchhits.h"
#include "searchparams.h"
#include "searchresultrenderer.h"
#include "utils.h"

class SearchTab : public QWidget {
    Q_OBJECT
public:
    SearchTab(QWidget* parent = 0);
    void append(const SearchHits& hits);
    void read();
    void trigRerender();
    SearchParams& params();
    SearchHits& hits();
    void setParams(const SearchParams& value);
    void setHits(const SearchHits& value);
    QTextBrowser* textBrowser() const;
    void setTextBrowser(QTextBrowser* value);
    DisplayOptionsWidget* displayOptions() const;
    void setDisplayOptions(DisplayOptionsWidget* value);
    SearchResultRenderer* renderer() const;
    void setRenderer(SearchResultRenderer* value);

protected:
    SearchParams mParams;
    SearchHits mHits;
    QTextBrowser* mTextBrowser;
    DisplayOptionsWidget* mDisplayOptions;
    SearchResultRenderer* mRenderer;
};

#endif // SEARCHTAB_H
