// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHPARAMS_H
#define SEARCHPARAMS_H
#include "regexp.h"
#include "regexppath.h"
#include "regexpreplacement.h"
#include <QMetaType>
#include <QString>

class SearchParams {

public:
    SearchParams();
    int id() const;
    void setId(int value);
    int mode() const;
    void setMode(int value);
    QString path() const;
    void setPath(const QString& value);
    RegExp pattern() const;
    void setPattern(const RegExp& value);
    RegExpPath filter() const;
    void setFilter(const RegExpPath& value);
    RegExpReplacement replacement() const;
    void setReplacement(const RegExpReplacement& value);
    bool cacheFileList() const;
    void setCacheFileList(bool value);
    bool skipBinary() const;
    void setSkipBinary(bool value);

protected:
    int mId;
    int mMode;
    QString mPath;
    RegExp mPattern;
    RegExpPath mFilter;
    RegExpReplacement mReplacement;
    bool mCacheFileList;
    bool mSkipBinary;
};

Q_DECLARE_METATYPE(SearchParams)

#endif // SEARCHPARAMS_H
