// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "searchdata.h"

SearchData::SearchData() : mFilesComplete(0) {
}
SearchData::SearchData(const QStringList& files, int filesFiltered, int dirsFiltered)
    : mFiles(files), mFilesFiltered(filesFiltered), mDirsFiltered(dirsFiltered), mFilesComplete(0) {
}
QStringList SearchData::files() const {
    return mFiles;
}
void SearchData::setFiles(const QStringList& value) {
    mFiles = value;
}
int SearchData::filesFiltered() const {
    return mFilesFiltered;
}
void SearchData::setFilesFiltered(int value) {
    mFilesFiltered = value;
}
int SearchData::dirsFiltered() const {
    return mDirsFiltered;
}
void SearchData::setDirsFiltered(int value) {
    mDirsFiltered = value;
}
int SearchData::filesComplete() const {
    return mFilesComplete;
}
void SearchData::setFilesComplete(int value) {
    mFilesComplete = value;
}
QString SearchData::file(int i) const {
    return mFiles[i];
}
int SearchData::filesSize() const {
    return mFiles.size();
}
