// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#ifndef SEARCHTAB_H
#define SEARCHTAB_H
#include <QString>
#include <QWidget>
class QTextBrowser;
#include "coloredline.h"
#include "displayoptionswidget.h"
#include "html.h"
#include "mode.h"
#include "searchhits.h"
#include "searchparams.h"
#include "searchresultrenderer.h"
#include "utils.h"

class SearchTab : public QWidget {
    Q_OBJECT
public:
    SearchTab(QWidget* parent = 0);
    void append(const SearchHits& hits);
    void read();
    void trigRerender();
    void setMode(Mode value);
    SearchParams& params();
    SearchHits& hits();
    DisplayOptions displayOptions() const;
    void setDisplayOptions(const DisplayOptions& value);
    ReplaceParams replaceParams();
    QString toPlainText() const;
    QString toHtml() const;
    Mode mode() const;
    void setParams(const SearchParams& value);
    void setHits(const SearchHits& value);
    QTextBrowser* textBrowser() const;
    void setTextBrowser(QTextBrowser* value);
    DisplayOptionsWidget* displayOptionsWidget() const;
    void setDisplayOptionsWidget(DisplayOptionsWidget* value);
    SearchResultRenderer* renderer() const;
    void setRenderer(SearchResultRenderer* value);

protected:
    Mode mMode;
    SearchParams mParams;
    SearchHits mHits;
    QTextBrowser* mTextBrowser;
    DisplayOptionsWidget* mDisplayOptionsWidget;
    SearchResultRenderer* mRenderer;
};

#endif // SEARCHTAB_H
