// DO NOT EDIT ** This file was generated by mugicpp ** DO NOT EDIT
#include "viewoptions.h"

ViewOptions::ViewOptions() : mSearch(false), mFilter(false), mDisplay(false), mNavigate(false) {
}
ViewOptions::ViewOptions(bool search, bool filter, bool display, bool navigate, bool cache)
    : mSearch(search), mFilter(filter), mDisplay(display), mNavigate(navigate), mCache(cache) {
}
bool ViewOptions::search() const {
    return mSearch;
}
void ViewOptions::setSearch(bool value) {
    mSearch = value;
}
bool ViewOptions::filter() const {
    return mFilter;
}
void ViewOptions::setFilter(bool value) {
    mFilter = value;
}
bool ViewOptions::display() const {
    return mDisplay;
}
void ViewOptions::setDisplay(bool value) {
    mDisplay = value;
}
bool ViewOptions::navigate() const {
    return mNavigate;
}
void ViewOptions::setNavigate(bool value) {
    mNavigate = value;
}
bool ViewOptions::cache() const {
    return mCache;
}
void ViewOptions::setCache(bool value) {
    mCache = value;
}
void ViewOptions::toggleSearch() {
    mSearch = !mSearch;
}
void ViewOptions::toggleFilter() {
    mFilter = !mFilter;
}
void ViewOptions::toggleDisplay() {
    mDisplay = !mDisplay;
}
void ViewOptions::toggleNavigate() {
    mNavigate = !mNavigate;
}
void ViewOptions::toggleCache() {
    mCache = !mCache;
}
bool ViewOptions::all() const {
    return mSearch && mFilter && mDisplay && mNavigate && mCache;
}
void ViewOptions::setAll(bool value) {
    mSearch = value;
    mFilter = value;
    mDisplay = value;
    mNavigate = value;
    mCache = value;
}
